### PR TITLE
Create delete workload

### PR DESCRIPTION
**Pull request by jayashreemohan29**
A workload that creates, writes into and then deletes files.

### CODE REVIEW

**Comment by vijay03** [comment]
Does ext4 pass this workload? Also, how does a user run this workload? We want users to be able to run this easily like rename.

**Comment by jayashreemohan29** [comment]
Yes, ext4 passes this test. You run this test just like the rename workload. Default number of files created is set to 3.

**Comment by vijay03** [comment]
Can you modify the README to point out how to run this test? Lets set the default number of files to 10.

**Comment by jayashreemohan29** [comment]
Oh you mean to run this as background process? Now that might not be as simple. Why can they not run it as a standalone?

**Comment by vijay03** [comment]
No, even for standalone, I don't think the README has a specific command to run this right? It will be useful to modify the README to do this.

**Pull request merged**
