### PR TITLE
Rename Bug in ext2

### PR DESCRIPTION
**Pull request by ashmrtn**
This will at least update the README and Makefile to run with the new error reporting system. It also adds a simple ext2 rename bug that CrashMonkey detects.

### CODE REVIEW

**Comment by vijay03** [comment]
Could we also add in a file or some bugs.md that shows the result of the ext2 test case?

**Comment by vijay03** [comment]
Could we add more detail to the output such as which file is missing? Right now all we know is that some file is missing.

**Comment by ashmrtn** [comment]
I would prefer to log that in a file rather than throwing it out on stdout. The file that is missing is dependent on the workload, so in a set of tests from a single workload, different files may cause that type of error. I would like to create another PR to handle writing specific errors out to a log file if that's alright.

**Comment by vijay03** [comment]
Sounds good.

**Pull request merged**
